
###
# LOGIN USER
# @name hacerlogin
POST {{url}}/{{version}}/users/login
Content-type: application/json

{
    "email": "juanan@gmail.com",
    "password": "JuanAntonio7"
}

//@authToken = {{hacerlogin.response.body.$.status}}

###
#POST forgot password
POST  {{url}}/{{version}}/users/forgotpass
content-type: application/json

{
    "email": "juanan@gmail.com"
}


###
#PATCH resetear password. se pasa el token de resetar password
@token=f5aa85e6c4b636170c2d76152aa2cf783f91a9ff72cccc7a3f8b6d3af56c4223
PATCH  {{url}}/{{version}}/users/resetpass/{{token}}
content-type: application/json

{
    "password": "JuanAntonio7",
    "passwordConfirm": "JuanAntonio7"
}


###
#PATCH Update password
@passwordToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2RmMGMzMjU0YjdmNTBiMGU1ZTMwZSIsImlhdCI6MTY0MjE4NzkyNCwiZXhwIjoxNjQyMzYwNzI0fQ.qJD7VKf3dXDXQ9KGjvo9jqke60C2NF7zua9jHd98e0g
PATCH  {{url}}/{{version}}/users/updatepass
Authorization: {{passwordToken}}
content-type: application/json

{
    "oldPassword":"JuanAntonio7",
    "password": "JuanAntonio8",
    "passwordConfirm": "JuanAntonio8"
}