

###
# @name getpost
GET https://jsonplaceholder.typicode.com/todos/1

@authToken = {{getpost.response.body.$.title}}


 
###
##
GET http://localhost:3000/api/v1/users/mytest
content-type: application/json

{
    "titlez": "{{authToken}}" 
}
