###
#OTRAS PRUEBAS
GET https://webhooks.click2sync.com/dow/gov/code/dev/middleware/orders.php?env=dev&vendorid=aeNoo7zi
C2SKey: AS8O05LCD26OABP770TDI83FE7HFS6I2

###
# @name getpost
GET https://jsonplaceholder.typicode.com/todos/1

@authToken = {{getpost.response.body.$.title}}


 
###
##
GET http://localhost:3000/api/v1/users/mytest
content-type: application/json

{
    "titlez": "{{authToken}}" 
}