@userid = 61afbcb50b1b191cf4de3a83
@url = http://localhost:3000
@version = api/v1

###
#Retrive all users //dejamos la url a modo de ejemplo
GET  http://localhost:3000/api/v1/users

###
#CREATE (POST) a user.
POST {{url}}/{{version}}/users/signup
content-type: application/json

{
    "name": "testandomasymas",
    "email": "siva2@testing.com",
    "password": "Testando1",
    "passwordConfirm":"Testando1",
    "role":"user"
}


###
#PATH user information by the user (usuarios autenticados actualizando sus datos)
PATCH {{url}}/{{version}}/

###
#GET one user
GET {{url}}/{{version}}/users/{{userid}}

###
#PATCH the user
PATCH {{url}}/{{version}}/users/9

###
#DELETE the user
DELETE  {{url}}/{{version}}/users/61cded3fb0776a1c50c91a8a

